version: "3.8"

x-env: &env
  HOARDER_VERSION: ${HOARDER_VERSION:-release}
  NEXTAUTH_SECRET: $NEXTAUTH_SECRET
  MEILI_MASTER_KEY: $MEILI_MASTER_KEY
  NEXTAUTH_URL: $SERVICE_FQDN_HOARDER
  DISABLE_SIGNUPS: ${DISABLE_SIGNUPS:-false}
  CRAWLER_FULL_PAGE_SCREENSHOT: ${CRAWLER_FULL_PAGE_SCREENSHOT:-false}
  CRAWLER_FULL_PAGE_ARCHIVE: ${CRAWLER_FULL_PAGE_ARCHIVE:-false}

services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/remote_docker_volume/Hoarder/data:/data
    environment:
      <<: *env
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    environment:
      <<: *env
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/remote_docker_volume/Hoarder/data:/data
    environment:
      <<: *env
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      OPENAI_BASE_URL: $OPENAI_BASE_URL
      OPENAI_API_KEY: $OPENAI_API_KEY
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
